/*
* Copyright (C) 2014, Fraunhofer Institute for Open Communication Systems FOKUS
*/

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cdmxdr.h"

bool_t
xdr_session (XDR *xdrs, session *objp)
{
  //register int32_t *buf;

   if (!xdr_string (xdrs, &objp->type, 128))
     return FALSE;
   if (!xdr_array (xdrs, (char **)&objp->pbInitData.pbInitData_val, (u_int *) &objp->pbInitData.pbInitData_len, ~0,
    sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
     return FALSE;
   if (!xdr_array (xdrs, (char **)&objp->pbCDMData.pbCDMData_val, (u_int *) &objp->pbCDMData.pbCDMData_len, ~0,
    sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
     return FALSE;
  return TRUE;
}

bool_t
xdr_data (XDR *xdrs, data *objp)
{
  //register int32_t *buf;

   if (!xdr_array (xdrs, (char **)&objp->pbIv.pbIv_val, (u_int *) &objp->pbIv.pbIv_len, ~0,
    sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
     return FALSE;
   if (!xdr_array (xdrs, (char **)&objp->pbData.pbData_val, (u_int *) &objp->pbData.pbData_len, ~0,
    sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
     return FALSE;
   if (!xdr_array (xdrs, (char **)&objp->session_id.session_id_val, (u_int *) &objp->session_id.session_id_len, ~0,
    sizeof (uint16_t), (xdrproc_t) xdr_uint16_t))
     return FALSE;
   if (!xdr_array (xdrs, (char **)&objp->subsampleData.subsampleData_val, (u_int *) &objp->subsampleData.subsampleData_len, ~0,
    sizeof (uint32_t), (xdrproc_t) xdr_uint32_t))
     return FALSE;
  return TRUE;
}

bool_t
xdr_decrypted_data (XDR *xdrs, decrypted_data *objp)
{
  //register int32_t *buf;

   if (!xdr_int32_t (xdrs, &objp->return_val))
     return FALSE;
   if (!xdr_array (xdrs, (char **)&objp->pbData.pbData_val, (u_int *) &objp->pbData.pbData_len, ~0,
    sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
     return FALSE;
   if (!xdr_array (xdrs, (char **)&objp->subsampleData.subsampleData_val, (u_int *) &objp->subsampleData.subsampleData_len, ~0,
    sizeof (uint32_t), (xdrproc_t) xdr_uint32_t))
     return FALSE;
  return TRUE;
}

bool_t
xdr_me_data (XDR *xdrs, me_data *objp)
{
  //register int32_t *buf;

   if (!xdr_array (xdrs, (char **)&objp->sampleProtectionCert.sampleProtectionCert_val, (u_int *) &objp->sampleProtectionCert.sampleProtectionCert_len, ~0,
    sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
     return FALSE;
   if (!xdr_array (xdrs, (char **)&objp->session_id.session_id_val, (u_int *) &objp->session_id.session_id_len, ~0,
    sizeof (uint16_t), (xdrproc_t) xdr_uint16_t))
     return FALSE;
   if (!xdr_int32_t (xdrs, &objp->idXchngShMem))
     return FALSE;
   if (!xdr_int32_t (xdrs, &objp->idXchngSem))
     return FALSE;
  return TRUE;
}

bool_t
xdr_mes_data (XDR *xdrs, mes_data *objp)
{
  //register int32_t *buf;

   if (!xdr_array (xdrs, (char **)&objp->mes_sid.mes_sid_val, (u_int *) &objp->mes_sid.mes_sid_len, ~0,
    sizeof (uint16_t), (xdrproc_t) xdr_uint16_t))
     return FALSE;
  return TRUE;
}

bool_t
xdr_mes_response (XDR *xdrs, mes_response *objp)
{
  //register int32_t *buf;

   if (!xdr_int32_t (xdrs, &objp->return_val))
     return FALSE;
   if (!xdr_array (xdrs, (char **)&objp->encryptedSessionKey.encryptedSessionKey_val, (u_int *) &objp->encryptedSessionKey.encryptedSessionKey_len, ~0,
    sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
     return FALSE;
  return TRUE;
}

bool_t
xdr_type_request (XDR *xdrs, type_request *objp)
{
  //register int32_t *buf;

   if (!xdr_array (xdrs, (char **)&objp->keysys.keysys_val, (u_int *) &objp->keysys.keysys_len, ~0,
    sizeof (uint16_t), (xdrproc_t) xdr_uint16_t))
     return FALSE;
   if (!xdr_array (xdrs, (char **)&objp->type.type_val, (u_int *) &objp->type.type_len, ~0,
    sizeof (uint16_t), (xdrproc_t) xdr_uint16_t))
     return FALSE;
  return TRUE;
}

bool_t
xdr_session_response (XDR *xdrs, session_response *objp)
{
  //register int32_t *buf;

   if (!xdr_int32_t (xdrs, &objp->return_val))
     return FALSE;
   if (!xdr_array (xdrs, (char **)&objp->session_id.session_id_val, (u_int *) &objp->session_id.session_id_len, ~0,
    sizeof (uint16_t), (xdrproc_t) xdr_uint16_t))
     return FALSE;
  return TRUE;
}

bool_t
xdr_params_run (XDR *xdrs, params_run *objp)
{
  //register int32_t *buf;

   if (!xdr_array (xdrs, (char **)&objp->session_id.session_id_val, (u_int *) &objp->session_id.session_id_len, ~0,
    sizeof (uint16_t), (xdrproc_t) xdr_uint16_t))
     return FALSE;
  return TRUE;
}

bool_t
xdr_params_update (XDR *xdrs, params_update *objp)
{
  //register int32_t *buf;

   if (!xdr_array (xdrs, (char **)&objp->session_id.session_id_val, (u_int *) &objp->session_id.session_id_len, ~0,
    sizeof (uint16_t), (xdrproc_t) xdr_uint16_t))
     return FALSE;
   if (!xdr_array (xdrs, (char **)&objp->challenge_response.challenge_response_val, (u_int *) &objp->challenge_response.challenge_response_len, ~0,
    sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
     return FALSE;
  return TRUE;
}

bool_t
xdr_params_close (XDR *xdrs, params_close *objp)
{
  //register int32_t *buf;

   if (!xdr_array (xdrs, (char **)&objp->session_id.session_id_val, (u_int *) &objp->session_id.session_id_len, ~0,
    sizeof (uint16_t), (xdrproc_t) xdr_uint16_t))
     return FALSE;
  return TRUE;
}
