/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "opencdm_xdr.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

rpc_response_generic *
rpc_open_cdm_is_type_supported_1(rpc_request_is_type_supported *argp, CLIENT *clnt)
{
	static rpc_response_generic clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_OPEN_CDM_IS_TYPE_SUPPORTED,
		(xdrproc_t) xdr_rpc_request_is_type_supported, (caddr_t) argp,
		(xdrproc_t) xdr_rpc_response_generic, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rpc_response_generic *
rpc_open_cdm_mediakeys_1(rpc_request_mediakeys *argp, CLIENT *clnt)
{
	static rpc_response_generic clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_OPEN_CDM_MEDIAKEYS,
		(xdrproc_t) xdr_rpc_request_mediakeys, (caddr_t) argp,
		(xdrproc_t) xdr_rpc_response_generic, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rpc_response_create_session *
rpc_open_cdm_mediakeys_create_session_1(rpc_request_create_session *argp, CLIENT *clnt)
{
	static rpc_response_create_session clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_OPEN_CDM_MEDIAKEYS_CREATE_SESSION,
		(xdrproc_t) xdr_rpc_request_create_session, (caddr_t) argp,
		(xdrproc_t) xdr_rpc_response_create_session, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rpc_response_generic *
rpc_open_cdm_mediakeys_load_session_1(rpc_request_load_session *argp, CLIENT *clnt)
{
	static rpc_response_generic clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_OPEN_CDM_MEDIAKEYS_LOAD_SESSION,
		(xdrproc_t) xdr_rpc_request_load_session, (caddr_t) argp,
		(xdrproc_t) xdr_rpc_response_generic, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rpc_response_generic *
rpc_open_cdm_mediakeysession_update_1(rpc_request_session_update *argp, CLIENT *clnt)
{
	static rpc_response_generic clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_OPEN_CDM_MEDIAKEYSESSION_UPDATE,
		(xdrproc_t) xdr_rpc_request_session_update, (caddr_t) argp,
		(xdrproc_t) xdr_rpc_response_generic, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rpc_response_generic *
rpc_open_cdm_mediakeysession_release_1(rpc_request_session_release *argp, CLIENT *clnt)
{
	static rpc_response_generic clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_OPEN_CDM_MEDIAKEYSESSION_RELEASE,
		(xdrproc_t) xdr_rpc_request_session_release, (caddr_t) argp,
		(xdrproc_t) xdr_rpc_response_generic, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rpc_response_generic *
rpc_open_cdm_mediaengine_1(rpc_request_mediaengine_data *argp, CLIENT *clnt)
{
	static rpc_response_generic clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_OPEN_CDM_MEDIAENGINE,
		(xdrproc_t) xdr_rpc_request_mediaengine_data, (caddr_t) argp,
		(xdrproc_t) xdr_rpc_response_generic, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
